require File.expand_path("lib/formatador_moeda")
require File.expand_path("lib/midia")
require File.expand_path("lib/livro")
require File.expand_path("lib/biblioteca")
require File.expand_path("lib/relatorio")
require File.expand_path("lib/banco_de_arquivo")
require File.expand_path("lib/dvd")
